#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    template = '({{ .Venv }}) '
    foreground = '#ff5533'
    home_enabled = true

  [[blocks.segments]]
    newline = true
    type = 'path'
    style = 'powerline'
    template = '[ {{ .Path }}] '
    background = 'p:#ffffff'
    foreground = '#ff5500'
    Text = ''

    [blocks.segments.properties]
      style = 'folder'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
  "#aa66ff"
    ]
    background = 'transparent'
    template = '[󰞷]-'

[transient_prompt]
  template = ''
  background = 'transparent'
  foreground = 'p:white'



[palette]
  black = '#262B44'
  blue = '#4B9580'
  green = '#52f8b5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
