#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    background = 'p:#ffffff, transparent'
    foreground = 'p:red'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    trailing_diamond = ''
    template = '  {{ path .Path .Location }} '
    background = ''
    foreground = 'p:white'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'folder'

[[tooltips]]
  type = 'aws'
  tips = ['aws']
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  background = 'p:blue'
  foreground = 'p:white'
  Text = ''
  Duration = 0
  NameLength = 0

  [tooltips.properties]
    display_default = true

[palette]
  black = '#262B44'
  blue = '#4B9580'
  green = '#52f8b5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
